    server {
        listen 80;

        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # 👇 fix SPA (React Router, Next static export)
        location / {
            try_files $uri /index.html;
        }

        # 👇 proxy API (optional - rất hay dùng)
        location /api/ {
            proxy_pass "http://host.docker.internal:8000/";

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;

            # resolver 127.0.0.11 valid=30s ipv6=off;
            # resolver_timeout 10s;
        }
    }